# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=1000)),
                ('url', models.URLField()),
                ('thumbnail', models.CharField(max_length=200)),
            ],
        ),
    ]
